name: Deploy Staging

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging ECS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            cd /app/resume-helper
            git pull origin develop || git pull origin main
            docker-compose pull || true
            docker-compose up -d --remove-orphans
            docker system prune -f

